export const LOCATIONS = {
  krsk: {
    townRu: 'красноярск',
    roditPadeg: 'красноярского',
    imageFolder: 'polovinka_uspeha',
    towns: [
      'Красноярск',
      'Сосновоборск',
      'Дивногорск',
      'Железногорск',
      'Дрокино',
      'Емельяново',
    ],
    hidden: false,
  },
  nrsk: {
    townRu: 'норильск',
    roditPadeg: 'норильского',
    imageFolder: 'polovinka_uspeha_nrsk',
    towns: ['Норильск', 'Талнах', 'Кайеркан', 'Оганер', 'Дудинка', 'Алыкель'],
    hidden: false,
  },
  ekb: {
    townRu: 'екатеринбург',
    roditPadeg: 'екатеринбуржского',
    imageFolder: 'polovinka_uspeha_ekb',
    towns: [
      'Екатеринбург',
      'Среднеуральск',
      'Нижний Тагил',
      'Полевской',
      'Верхняя Пышма',
      'Березовский',
    ],
    hidden: false,
  },
}

export const LOCATIONS_KEYS_VISIBLE = Object.keys(LOCATIONS).filter(
  (location) => !LOCATIONS[location].hidden
)

export const MONTHS = [
  'янв',
  'фев',
  'мар',
  'апр',
  'май',
  'июн',
  'июл',
  'авг',
  'сен',
  'окт',
  'ноя',
  'дек',
]

export const MONTHS_FULL_1 = [
  'январь',
  'февраль',
  'март',
  'апрель',
  'май',
  'июнь',
  'июль',
  'август',
  'сентябрь',
  'октябрь',
  'ноябрь',
  'декабрь',
]

export const MONTHS_FULL = [
  'января',
  'февраля',
  'марта',
  'апреля',
  'мая',
  'июня',
  'июля',
  'августа',
  'сентября',
  'октября',
  'ноября',
  'декабря',
]

export const DAYS_OF_WEEK = ['ВС', 'ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ']

export const DAYS_OF_WEEK_FULL = [
  'воскресенье',
  'понедельник',
  'вторник',
  'среда',
  'четверг',
  'пятница',
  'суббота',
]

export const DEFAULT_USERS_SECURITY = Object.freeze({
  fullSecondName: true,
  fullThirdName: true,
  showBirthday: true,
  showPhone: false,
  showWhatsapp: false,
  showViber: false,
  showTelegram: false,
  showInstagram: false,
  showVk: false,
  showEmail: false,
})

export const DEFAULT_USERS_NOTIFICATIONS = Object.freeze({
  telegram: { active: false, userName: null, id: null },
  settings: {},
})

export const DEFAULT_USERS_STATUS_ACCESS = {
  noReg: true,
  novice: true,
  member: true,
}

export const DEFAULT_USERS_STATUS_DISCOUNT = {
  novice: 0,
  member: 0,
}

export const DEFAULT_ADDRESS = Object.freeze({
  town: '',
  street: '',
  house: '',
  entrance: '',
  floor: '',
  flat: '',
  comment: '',
  link2Gis: '',
  linkYandexNavigator: '',
  link2GisShow: true,
  linkYandexShow: true,
})

export const DEFAULT_EVENT = Object.freeze({
  directionId: null,
  organizerId: null,
  title: '',
  description: '',
  dateStart: null,
  dateEnd: null,
  address: DEFAULT_ADDRESS,
  status: 'active',
  images: [],
  showOnSite: true,
  report: '',
  reportImages: [],
  warning: false,
  likes: false,
  likesProcessActive: true,
  blank: false,
})

export const DEFAULT_SUBEVENT = Object.freeze({
  title: '',
  description: '',
  price: 0,
  maxParticipants: null,
  maxMans: null,
  maxWomans: null,
  maxMansNovice: null,
  maxWomansNovice: null,
  maxMansMember: null,
  maxWomansMember: null,
  minMansAge: 35,
  minWomansAge: 30,
  maxMansAge: 50,
  maxWomansAge: 45,
  usersStatusAccess: {},
  usersStatusDiscount: {},
  usersRelationshipAccess: 'yes',
  isReserveActive: true,
})

export const DEFAULT_SERVICE_USER = Object.freeze({
  userId: '',
  serviceId: '',
  answers: {},
  status: 'active',
})

export const DEFAULT_USER = Object.freeze({
  firstName: '',
  secondName: '',
  thirdName: '',
  password: '',
  email: '',
  phone: null,
  whatsapp: null,
  viber: null,
  telegram: '',
  vk: '',
  instagram: '',
  birthday: null,
  gender: null,
  images: [],
  role: 'client',
  relationship: null,
  town: '',
  personalStatus: '',
  status: 'novice',
  lastActivityAt: null,
  prevActivityAt: null,
  archive: false,
  haveKids: null,
  security: DEFAULT_USERS_SECURITY,
  notifications: DEFAULT_USERS_NOTIFICATIONS,
})

export const DEFAULT_ROLES = [
  {
    _id: 'client',
    name: 'Пользователь',
    hidden: false,
    dev: false,
    seeMyStatistics: false,
    setSelfStatus: false,
    setSelfRole: false,
    hideFab: false,
    notifications: {
      // option: true,
      birthdays: false,
      newUserRegistred: false,
      eventRegistration: false,
      serviceRegistration: false,
      newEventsByTags: true,
      remindDates: false,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: false,
      add: false,
      edit: false,
      delete: false,
      statusEdit: false,
      paymentsEdit: false,
      showProfitOnCard: false,
      statusFilterFull: false,
      seeReserveOnCard: false,
      eventUsersCounterAndAgeFull: false,
      seeHistory: false,
      editLikes: false,
      sendNotifications: false,
    },
    eventsUsers: {
      see: false, // member
      edit: false,
      copyListToClipboard: false,
      seeHistory: false,
    },
    users: {
      see: false,
      seeMembersOnly: false,
      seeFullNames: false,
      seeAllContacts: false,
      seeBirthday: false,
      seeUserEvents: false,
      seeUserPayments: false,
      setPassword: false,
      seeSumOfPaymentsWithoutEventOnCard: false,
      add: false,
      edit: false,
      setRole: false,
      setStatus: false,
      delete: false,
      seeHistory: false,
      seeActionsHistory: false,
      seeNotificationIconOnCard: false,
    },
    services: {
      see: true,
      seeHidden: false,
      add: false,
      edit: false,
      delete: false,
      seeHistory: false,
    },
    servicesUsers: {
      see: false,
      add: false,
      edit: false,
      delete: false,
      statusEdit: false,
    },
    products: {
      see: false,
      seeHidden: false,
      add: false,
      edit: false,
      delete: false,
      seeHistory: false,
    },
    productsUsers: {
      see: false,
      add: false,
      edit: false,
      delete: false,
      statusEdit: true,
    },
    payments: {
      see: false,
      add: false,
      edit: false,
      delete: false,
      paymentsNotParticipantsEvent: false,
      paymentsWithNoEvent: false,
      seeHistory: false,
    },
    statistics: {
      events: false,
      users: false,
      finances: false,
    },
    instruments: {
      anonsTextGenerator: false,
      anonsEventImageGenerator: false,
      anonsEventListImageGenerator: false,
      export: false,
      imageConstructor: false,
      individualWeddings: false,
    },
    newsletters: {
      see: false,
      add: false,
      delete: false,
    },
    generalPage: {
      directions: false,
      additionalBlocks: false,
      reviews: false,
      supervisor: false,
      contacts: false,
      siteTitleSettings: false,
    },
    siteSettings: {
      phoneConfirmService: false,
      fabMenu: false,
      referralSystem: false,
      achievements: false,
      roles: false,
      dateStartProject: false,
      headerInfo: false,
      remindDatesEdit: false,
    },
    notices: {
      histories: false,
      birthdays: false,
    },
  },
  {
    _id: 'moder',
    name: 'Модератор',
    hidden: false,
    dev: false,
    seeMyStatistics: false,
    setSelfStatus: false,
    setSelfRole: false,
    hideFab: true,
    notifications: {
      // option: true,
      birthdays: false,
      newUserRegistred: false,
      eventRegistration: false,
      serviceRegistration: false,
      newEventsByTags: false,
      remindDates: true,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: false,
      statusEdit: false,
      paymentsEdit: true,
      showProfitOnCard: false,
      statusFilterFull: true,
      seeReserveOnCard: true,
      eventUsersCounterAndAgeFull: true,
      seeHistory: false,
      editLikes: false,
      sendNotifications: false,
    },
    eventsUsers: {
      see: true, // member
      edit: true,
      copyListToClipboard: true,
      seeHistory: true,
    },
    users: {
      see: true,
      seeMembersOnly: false,
      seeFullNames: true,
      seeAllContacts: true,
      seeBirthday: true,
      seeUserEvents: true,
      seeUserPayments: false,
      setPassword: false,
      seeSumOfPaymentsWithoutEventOnCard: false,
      add: true,
      edit: true,
      setRole: false,
      setStatus: true,
      delete: false,
      seeHistory: false,
      seeActionsHistory: false,
      seeNotificationIconOnCard: true,
    },
    services: {
      see: true,
      seeHidden: true,
      add: false,
      edit: false,
      delete: false,
      seeHistory: false,
    },
    servicesUsers: {
      see: true,
      add: false,
      edit: false,
      delete: false,
      statusEdit: false,
    },
    products: {
      see: true,
      seeHidden: false,
      add: false,
      edit: false,
      delete: false,
      seeHistory: false,
    },
    productsUsers: {
      see: true,
      add: false,
      edit: false,
      delete: false,
      statusEdit: false,
    },
    payments: {
      see: false,
      add: false,
      edit: false,
      delete: false,
      paymentsNotParticipantsEvent: false,
      paymentsWithNoEvent: false,
      seeHistory: false,
    },
    statistics: {
      events: false,
      users: false,
      finances: false,
    },
    instruments: {
      anonsTextGenerator: true,
      anonsEventImageGenerator: true,
      anonsEventListImageGenerator: true,
      export: true,
      imageConstructor: false,
      individualWeddings: false,
    },
    newsletters: {
      see: false,
      add: false,
      delete: false,
    },
    generalPage: {
      directions: true,
      additionalBlocks: true,
      reviews: true,
      supervisor: false,
      contacts: false,
      siteTitleSettings: false,
    },
    siteSettings: {
      phoneConfirmService: false,
      fabMenu: false,
      referralSystem: false,
      achievements: false,
      roles: false,
      dateStartProject: false,
      headerInfo: false,
      remindDatesEdit: false,
    },
    notices: {
      histories: true,
      birthdays: true,
    },
  },
  {
    _id: 'admin',
    name: 'Администратор',
    hidden: false,
    dev: false,
    seeMyStatistics: true,
    setSelfStatus: false,
    setSelfRole: false,
    hideFab: true,
    notifications: {
      // option: true,
      birthdays: true,
      newUserRegistred: true,
      eventRegistration: true,
      serviceRegistration: true,
      newEventsByTags: true,
      remindDates: true,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: false,
      statusEdit: false,
      paymentsEdit: true,
      showProfitOnCard: false,
      statusFilterFull: true,
      seeReserveOnCard: true,
      eventUsersCounterAndAgeFull: true,
      seeHistory: false,
      editLikes: false,
      sendNotifications: false,
    },
    eventsUsers: {
      see: true, // member
      edit: true,
      copyListToClipboard: true,
      seeHistory: true,
    },
    users: {
      see: true,
      seeMembersOnly: false,
      seeFullNames: true,
      seeAllContacts: true,
      seeBirthday: true,
      seeUserEvents: true,
      seeUserPayments: true,
      setPassword: false,
      seeSumOfPaymentsWithoutEventOnCard: true,
      add: true,
      edit: true,
      setRole: false,
      setStatus: true,
      delete: false,
      seeHistory: false,
      seeActionsHistory: false,
      seeNotificationIconOnCard: true,
    },
    services: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: false,
      seeHistory: false,
    },
    servicesUsers: {
      see: true,
      add: true,
      edit: true,
      delete: false,
      statusEdit: true,
    },
    products: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: false,
      seeHistory: false,
    },
    productsUsers: {
      see: true,
      add: true,
      edit: true,
      delete: false,
      statusEdit: true,
    },
    payments: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      paymentsNotParticipantsEvent: true,
      paymentsWithNoEvent: true,
      seeHistory: false,
    },
    statistics: {
      events: false,
      users: false,
      finances: false,
    },
    instruments: {
      anonsTextGenerator: true,
      anonsEventImageGenerator: true,
      anonsEventListImageGenerator: true,
      export: true,
      imageConstructor: false,
      individualWeddings: false,
    },
    newsletters: {
      see: false,
      add: false,
      delete: false,
    },
    generalPage: {
      directions: true,
      additionalBlocks: true,
      reviews: true,
      supervisor: false,
      contacts: true,
      siteTitleSettings: false,
    },
    siteSettings: {
      phoneConfirmService: false,
      fabMenu: false,
      referralSystem: false,
      achievements: false,
      roles: false,
      dateStartProject: false,
      headerInfo: false,
      remindDatesEdit: true,
    },
    notices: {
      histories: true,
      birthdays: true,
    },
  },
  {
    _id: 'supervisor',
    name: 'Руководитель филиала',
    hidden: false,
    dev: false,
    seeMyStatistics: true,
    setSelfStatus: true,
    setSelfRole: false,
    hideFab: true,
    notifications: {
      // option: true,
      birthdays: true,
      newUserRegistred: true,
      eventRegistration: true,
      serviceRegistration: true,
      newEventsByTags: true,
      remindDates: true,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
      paymentsEdit: true,
      showProfitOnCard: true,
      statusFilterFull: true,
      seeReserveOnCard: true,
      eventUsersCounterAndAgeFull: true,
      seeHistory: true,
      editLikes: true,
      sendNotifications: true,
    },
    eventsUsers: {
      see: true, // member
      edit: true,
      copyListToClipboard: true,
      seeHistory: true,
    },
    users: {
      see: true,
      seeMembersOnly: false,
      seeFullNames: true,
      seeAllContacts: true,
      seeBirthday: true,
      seeUserEvents: true,
      seeUserPayments: true,
      setPassword: true,
      seeSumOfPaymentsWithoutEventOnCard: true,
      add: true,
      edit: true,
      setRole: true,
      setStatus: true,
      delete: true,
      seeHistory: true,
      seeActionsHistory: true,
      seeNotificationIconOnCard: true,
    },
    services: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    servicesUsers: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
    },
    products: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    productsUsers: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
    },
    payments: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      paymentsNotParticipantsEvent: true,
      paymentsWithNoEvent: true,
      seeHistory: true,
    },
    statistics: {
      events: true,
      users: true,
      finances: true,
    },
    instruments: {
      anonsTextGenerator: true,
      anonsEventImageGenerator: true,
      anonsEventListImageGenerator: true,
      export: true,
      imageConstructor: false,
      individualWeddings: false,
    },
    newsletters: {
      see: true,
      add: true,
      delete: true,
    },
    generalPage: {
      directions: true,
      additionalBlocks: true,
      reviews: true,
      supervisor: true,
      contacts: true,
      siteTitleSettings: true,
    },
    siteSettings: {
      phoneConfirmService: false,
      fabMenu: true,
      referralSystem: true,
      achievements: true,
      roles: true,
      dateStartProject: false,
      headerInfo: true,
      remindDatesEdit: true,
    },
    notices: {
      histories: true,
      birthdays: true,
    },
  },
  {
    _id: 'president',
    name: 'Руководитель проекта',
    hidden: false,
    dev: false,
    seeMyStatistics: true,
    setSelfStatus: true,
    setSelfRole: false,
    hideFab: true,
    notifications: {
      // option: true,
      birthdays: true,
      newUserRegistred: true,
      eventRegistration: true,
      serviceRegistration: true,
      newEventsByTags: true,
      remindDates: true,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
      paymentsEdit: true,
      showProfitOnCard: true,
      statusFilterFull: true,
      seeReserveOnCard: true,
      eventUsersCounterAndAgeFull: true,
      seeHistory: true,
      editLikes: true,
      sendNotifications: true,
    },
    eventsUsers: {
      see: true, // member
      edit: true,
      copyListToClipboard: true,
      seeHistory: true,
    },
    users: {
      see: true,
      seeMembersOnly: false,
      seeFullNames: true,
      seeAllContacts: true,
      seeBirthday: true,
      seeUserEvents: true,
      seeUserPayments: true,
      setPassword: true,
      seeSumOfPaymentsWithoutEventOnCard: true,
      add: true,
      edit: true,
      setRole: true,
      setStatus: true,
      delete: true,
      seeHistory: true,
      seeActionsHistory: true,
      seeNotificationIconOnCard: true,
    },
    services: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    servicesUsers: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
    },
    products: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    productsUsers: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
    },
    payments: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      paymentsNotParticipantsEvent: true,
      paymentsWithNoEvent: true,
      seeHistory: true,
    },
    statistics: {
      events: true,
      users: true,
      finances: true,
    },
    instruments: {
      anonsTextGenerator: true,
      anonsEventImageGenerator: true,
      anonsEventListImageGenerator: true,
      export: true,
      imageConstructor: false,
      individualWeddings: true,
    },
    newsletters: {
      see: true,
      add: true,
      delete: true,
    },
    generalPage: {
      directions: true,
      additionalBlocks: true,
      reviews: true,
      supervisor: true,
      contacts: true,
      siteTitleSettings: true,
    },
    siteSettings: {
      phoneConfirmService: false,
      fabMenu: true,
      referralSystem: true,
      achievements: true,
      roles: true,
      dateStartProject: false,
      headerInfo: true,
      remindDatesEdit: true,
    },
    notices: {
      histories: true,
      birthdays: true,
    },
  },
  {
    _id: 'dev',
    name: 'Разработчик',
    hidden: false,
    dev: true,
    seeMyStatistics: true,
    setSelfStatus: true,
    setSelfRole: true,
    hideFab: true,
    notifications: {
      // option: true,
      birthdays: true,
      newUserRegistred: true,
      eventRegistration: true,
      serviceRegistration: true,
      newEventsByTags: true,
      remindDates: true,
      // eventUserMoves: false,
      // eventCancel: false,
    },
    events: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
      paymentsEdit: true,
      showProfitOnCard: true,
      statusFilterFull: true,
      seeReserveOnCard: true,
      eventUsersCounterAndAgeFull: true,
      seeHistory: true,
      editLikes: true,
      sendNotifications: true,
    },
    eventsUsers: {
      see: true, // ! member
      edit: true,
      copyListToClipboard: true,
      seeHistory: true,
    },
    users: {
      see: true,
      seeMembersOnly: false,
      seeFullNames: true,
      seeAllContacts: true,
      seeBirthday: true,
      seeUserEvents: true,
      seeUserPayments: true,
      setPassword: true,
      seeSumOfPaymentsWithoutEventOnCard: true,
      add: true,
      edit: true,
      setRole: true,
      setStatus: true,
      delete: true,
      seeHistory: true,
      seeActionsHistory: true,
      seeNotificationIconOnCard: true,
    },
    services: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    servicesUsers: {
      see: true,
      add: true,
      edit: true, // !
      delete: true,
      statusEdit: true,
    },
    products: {
      see: true,
      seeHidden: true,
      add: true,
      edit: true,
      delete: true,
      seeHistory: true,
    },
    productsUsers: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      statusEdit: true,
    },
    payments: {
      see: true,
      add: true,
      edit: true,
      delete: true,
      paymentsNotParticipantsEvent: true,
      paymentsWithNoEvent: true,
      seeHistory: true,
    },
    statistics: {
      events: true,
      users: true,
      finances: true,
    },
    instruments: {
      anonsTextGenerator: true,
      anonsEventImageGenerator: true,
      anonsEventListImageGenerator: true,
      export: true,
      imageConstructor: true,
      individualWeddings: true,
    },
    newsletters: {
      see: true,
      add: true,
      delete: true,
    },
    generalPage: {
      directions: true,
      additionalBlocks: true,
      reviews: true,
      supervisor: true,
      contacts: true,
      siteTitleSettings: true,
    },
    siteSettings: {
      phoneConfirmService: true,
      fabMenu: true,
      referralSystem: true,
      achievements: true,
      roles: true,
      dateStartProject: true,
      headerInfo: true,
      remindDatesEdit: true,
    },
    notices: {
      histories: true,
      birthdays: true,
    },
  },
]

