import {
  faCalendarDay,
  faCheckCircle,
  faCircle,
  faClock,
  faComments,
  faGift,
  faMars,
  faTimesCircle,
  faVenus,
} from '@fortawesome/free-solid-svg-icons'
import isDevMode from './isDevMode'

export const DEFAULT_USER = {
  name: 'Гость',
  email: '',
  phone: null,
  whatsapp: null,
  viber: null,
  telegram: null,
  vk: null,
  instagram: null,
  birthday: null,
  gender: null,
  image: null,
  role: 'client',
  subRoles: [],
}

export const GENDERS = [
  { value: 'male', name: 'Мужчина', color: 'blue-400', icon: faMars },
  { value: 'famale', name: 'Женщина', color: 'red-400', icon: faVenus },
]

export const CLOUDINARY_FOLDER = isDevMode
  ? 'obnimisharik_courses_dev'
  : 'obnimisharik_courses'

export const MODES = Object.freeze({
  ADMIN: 'admin',
  TEACHER: 'teacher',
  STUDENT: 'student',
  VIEWER: 'viewer',
})

export const MODES_NAMES = {
  [MODES.ADMIN]: 'Администратор',
  [MODES.TEACHER]: 'Преподаватель',
  [MODES.STUDENT]: 'Студент',
  [MODES.VIEWER]: 'Наблюдатель',
}

// import {
//   BtnAddClient,
//   BtnAddDevToDo,
//   BtnAddInvitation,
//   BtnAddOrder,
//   BtnAddPayment,
//   BtnAddProduct,
//   BtnAddProductCirculation,
//   BtnAddProductType,
//   BtnAddSet,
//   BtnAddSetType,
//   BtnTest,
//   BtnAddDistrict,
// } from '@admincomponents/TitleButtons'
import {
  faBug,
  faChartBar,
  faCog,
  faCubes,
  faFilter,
  faFire,
  faHome,
  faMoneyBill,
  faUser,
  faHeart,
} from '@fortawesome/free-solid-svg-icons'
import { faCalendar, faCalendarAlt } from '@fortawesome/free-regular-svg-icons'
// import {
//   InvitationsContent,
//   ProductCirculationsContent,
//   ProductsContent,
//   ProductTypesContent,
//   SetsContent,
//   SettingsContent,
//   SetTypesContent,
//   TestContent,
//   UserContent,
//   UsersContent,
//   OverviewContent,
//   ClientsContent,
//   OrdersContent,
//   PaymentsContent,
//   DistrictsContent,
// } from './content'
// import DevToDoContent from './content/DevToDoContent'

export const pages = [
  {
    id: 0,
    group: 0,
    name: 'Направления',
    href: 'directions',
    icon: faHeart,
    // pageContent: OverviewContent,
    // addButton: null,
    // backToPageId: null,
    // variable: null,
  },
  {
    id: 1,
    group: 0,
    name: 'Сертификат',
    href: 'sertificat',
    icon: faGift,
    // pageContent: OverviewContent,
    // addButton: null,
    // backToPageId: null,
    // variable: null,
  },
  {
    id: 2,
    group: 0,
    name: 'Отзывы',
    href: 'reviews',
    icon: faComments,
    // pageContent: OverviewContent,
    // addButton: null,
    // backToPageId: null,
    // variable: null,
  },
  {
    id: 3,
    group: 1,
    name: 'Мероприятия',
    href: 'events',
    icon: faCalendar,
    // pageContent: OverviewContent,
    // addButton: null,
    // backToPageId: null,
    // variable: null,
  },
  // {
  //   id: 4,
  //   group: 1,
  //   name: 'тест',
  //   href: 'events',
  //   icon: faCalendar,
  //   // pageContent: OverviewContent,
  //   // addButton: null,
  //   // backToPageId: null,
  //   // variable: null,
  // },
  // {
  //   id: 1,
  //   group: 1,
  //   name: 'Товары',
  //   // pageContent: ProductsContent,
  //   // addButton: BtnAddProduct,
  //   backToPageId: null,
  //   variable: 'products',
  // },
  // {
  //   id: 2,
  //   group: 1,
  //   name: 'Типы товаров',
  //   // pageContent: ProductTypesContent,
  //   // addButton: BtnAddProductType,
  //   backToPageId: null,
  //   variable: 'productTypes',
  // },
  // {
  //   id: 3,
  //   group: 1,
  //   name: 'Наборы',
  //   // pageContent: SetsContent,
  //   // addButton: BtnAddSet,
  //   backToPageId: null,
  //   variable: 'sets',
  // },
  // {
  //   id: 4,
  //   group: 1,
  //   name: 'Типы наборов',
  //   // pageContent: SetTypesContent,
  //   // addButton: BtnAddSetType,
  //   backToPageId: null,
  //   variable: 'setTypes',
  // },
  // {
  //   id: 5,
  //   group: null,
  //   name: 'Параметры учетной записи',
  //   // pageContent: UserContent,
  //   // addButton: null,
  //   backToPageId: null,
  //   variable: null,
  // },
  // {
  //   id: 6,
  //   group: 6,
  //   name: 'Сотрудники',
  //   // pageContent: UsersContent,
  //   // addButton: null,
  //   backToPageId: null,
  //   variable: 'users',
  // },
  // {
  //   id: 7,
  //   group: 6,
  //   name: 'Приглашения сотрудников',
  //   // pageContent: InvitationsContent,
  //   // addButton: BtnAddInvitation,
  //   backToPageId: null,
  //   variable: 'invitations',
  // },
  // {
  //   id: 9,
  //   group: 1,
  //   name: 'Движение товаров',
  //   // pageContent: ProductCirculationsContent,
  //   // addButton: BtnAddProductCirculation,
  //   backToPageId: 0,
  //   variable: 'productCirculations',
  // },
  // {
  //   id: 10,
  //   group: 3,
  //   name: 'Клиенты',
  //   // pageContent: ClientsContent,
  //   // addButton: BtnAddClient,
  //   backToPageId: 0,
  //   variable: 'clients',
  // },
  // {
  //   id: 11,
  //   group: 2,
  //   name: 'Заказы',
  //   // pageContent: OrdersContent,
  //   // addButton: BtnAddOrder,
  //   backToPageId: 0,
  //   variable: 'orders',
  // },
  // {
  //   id: 12,
  //   group: 4,
  //   name: 'Транзакции',
  //   // pageContent: PaymentsContent,
  //   // addButton: BtnAddPayment,
  //   backToPageId: 0,
  //   variable: 'payments',
  // },
  // {
  //   id: 99,
  //   group: 10,
  //   name: 'Тестовая страница',
  //   // pageContent: TestContent,
  //   // addButton: BtnTest,
  //   backToPageId: 0,
  //   variable: 'dev',
  // },
  // {
  //   id: 13,
  //   group: 0,
  //   name: 'Аэродизайнер',
  //   pageContent: OrdersContent,
  //   pageButtons: [],
  //   backToPageId: 0,
  //   accessRoles: ['aerodesigner'],
  //   variable: 'orders',
  // },
  // {
  //   id: 14,
  //   group: 0,
  //   name: 'Курьер',
  //   pageContent: OrdersContent,
  //   pageButtons: [],
  //   backToPageId: 0,
  //   accessRoles: ['deliver'],
  //   variable: 'orders',
  // },
  // {
  //   id: 15,
  //   group: 10,
  //   name: 'Заявки разработчику',
  //   // pageContent: DevToDoContent,
  //   // addButton: BtnAddDevToDo,
  //   backToPageId: 0,
  //   variable: 'devToDo',
  // },
  // {
  //   id: 16,
  //   group: 6,
  //   name: 'Районы доставки',
  //   // pageContent: DistrictsContent,
  //   // addButton: BtnAddDistrict,
  //   backToPageId: 0,
  //   variable: 'districts',
  // },
  // {
  //   id: 8,
  //   group: 6,
  //   name: 'Настройки CRM',
  //   // pageContent: SettingsContent,
  //   // addButton: null,
  //   backToPageId: 0,
  //   variable: null,
  // },
]

export const pagesGroups = [
  { id: 0, name: 'Сайт', icon: faHome },
  { id: 1, name: 'Мероприятия', icon: faCalendarAlt },
  // { id: 2, name: 'Заказы', icon: faFire },
  // { id: 1, name: 'Склад', icon: faCubes },
  // { id: 3, name: 'Клиенты', icon: faUser },
  // { id: 4, name: 'Оплата', icon: faMoneyBill },
  // { id: 6, name: 'Настройки', icon: faCog, bottom: true },
  // { id: 10, name: 'Разработка', icon: faBug, bottom: true },
]
