export const CABINET_PAGE_TITLES = Object.freeze({
  services: 'Услуги / Список услуг',
  products: 'Товары / Список товаров',
  servicesUsers: 'Услуги / Заявки на услуги',
  myServices: 'Услуги / Мои заявки на услуги',
  productsUsers: 'Товары / Заявки на товары',
  myProducts: 'Товары / Мои заявки на товары',
  directions: 'Сайт / Пространства',
  aboutSpace: 'Сайт / О нашем пространстве',
  closedSpace: 'Сайт / Закрытое пространство',
  reviews: 'Сайт / Отзывы',
  additionalBlocks: 'Сайт / Доп. блоки',
  spaceStats: 'Сайт / Пространство в цифрах',
  contacts: 'Сайт / Контакты на сайте',
  siteTitleSettings: 'Сайт / Заголовоки',
  supervisor: 'Сайт / Руководитель региона',
  founder: 'Сайт / Основатель проекта',
  eventsUpcoming: 'Предстоящие мероприятия',
  eventsPast: 'Прошедшие мероприятия',
  eventsCalendar: 'Календарь мероприятий',
  questionnaire: 'Мой профиль',
  notifications: 'Уведомления',
  googleCalendarIntegration: 'Интеграция Google календаря',
  users: 'Пользователи',
  members: 'Участники клуба',
  payments: 'Транзакции / Все транзакции',
  paymentsNotParticipantsEvent: 'Транзакции / Не пришли на мероприятие',
  paymentsForNotExistedEvents:
    'Транзакции / Со ссылками на несуществующие мероприятия',
  paymentsFromNotExistedUsers:
    'Транзакции / Со ссылками на несуществующих пользователей',
  dev: 'Разработчик',
  whatsappMessaging: 'Рассылка WhatsApp',
  toolsTextEventsAnons: 'Инструменты / Генератор текста анонса мероприятий',
  toolsEventAnonsInstagram: 'Инструменты / Редактор анонса в Instagram',
  toolsEventAnonsVk: 'Инструменты / Редактор анонса в VK',
  toolsAnons: 'Инструменты / Редактор анонса списка мероприятий',
  toolsImageConstructor: 'Инструменты / Конструктор картинок',
  toolsExport: 'Инструменты / Экспорт данных',
  toolsIndividualWeddings: 'Инструменты / Индивидуальные свидания',
  newsletter: 'Инструменты / Рассылка',
  histories: 'События / Записи на мероприятия',
  birthdays: 'События / Дни рождения',
  statisticsFinance: 'Статистика / Финансы',
  statisticsUsers: 'Статистика / Пользователи',
  statisticsEvents: 'Статистика / Мероприятия',
  settingsCodeSendService: 'Настройки / Сервис подтверждения номера',
  settingsFabMenu: 'Настройки / Меню "Вопрос"',
  settingsAchievements: 'Настройки / Достижения',
  settingsReferralSystem: 'Настройки / Реферальная система',
  settingsDateStartProject: 'Настройки / Дата старта проекта',
  settingsRoles: 'Настройки / Роли',
  settingsHeaderInfoContacts: 'Настройки / Информация для вступления в клуб',
  userStatistics: 'Моя статистика',
  referrals: 'Реферальная программа',
  referralsAdmin: 'Реферальная программа / Администрирование',
  likes: 'Лайки',
  remindDates: 'Особые даты ПУ',
})
